CREATE TABLE IF NOT EXISTS work_artifacts (
    artifact_id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    artifact_type TEXT,
    role TEXT,
    department TEXT,
    domain TEXT,
    difficulty TEXT,
    status TEXT,
    required_competencies TEXT,
    source_type TEXT,
    rag_enabled INTEGER,
    quiz_enabled INTEGER,
    description TEXT,
    skills TEXT
);

INSERT INTO work_artifacts VALUES ('WA-2025-001', 'Annual District-Level Employment Statistics Report – 2025', 'Statistical Report', 'Statistical Officer', 'Directorate of Economics & Statistics', 'Employment Statistics', 'Intermediate', 'Completed', 'Data Analysis & Interpretation | Statistical Sampling | Survey Methodology | Data Quality Management | Report Writing', 'Internal Work Artifact', 1, 1, 'District-level employment indicators based on household survey data, including labour-force participation, worker population ratio and unemployment rate.', 'data validation | sampling weights | trend analysis | statistical reporting');
INSERT INTO work_artifacts VALUES ('WA-2025-002', 'Quarterly Consumer Price Index Compilation Note – Q2 2025', 'Technical Note', 'Assistant Director', 'Price Statistics Division', 'Price Statistics', 'Advanced', 'Completed', 'Index Number Methods | Data Validation | Statistical Analysis | Quality Assurance | Technical Documentation', 'Internal Work Artifact', 1, 1, 'Technical documentation for compiling and validating quarterly consumer price indicators from collected market-price observations.', 'CPI calculation | index numbers | validation rules | quality assurance');
INSERT INTO work_artifacts VALUES ('WA-2025-003', 'Household Survey Data Cleaning and Validation Report', 'Data Quality Report', 'Data Analyst', 'Survey Processing Unit', 'Survey Data Management', 'Intermediate', 'Completed', 'Data Cleaning | Missing Value Treatment | Outlier Detection | Data Quality Management | Python/Pandas', 'Internal Work Artifact', 1, 1, 'Report documenting missing-value checks, duplicate detection, outlier investigation and validation of a household survey dataset.', 'missing values | outliers | duplicates | data profiling | pandas');
INSERT INTO work_artifacts VALUES ('WA-2025-004', 'Sampling Design for Rural Socio-Economic Survey', 'Methodology Document', 'Research Officer', 'Survey Methodology Division', 'Survey Methodology', 'Advanced', 'Under Review', 'Sampling Theory | Stratified Sampling | Sample Size Determination | Survey Design | Statistical Inference', 'Internal Work Artifact', 1, 1, 'Proposed sampling design covering strata formation, sample allocation and selection procedures for a rural socio-economic survey.', 'stratified sampling | sample allocation | sampling frame | inference');
INSERT INTO work_artifacts VALUES ('WA-2025-005', 'District GDP Estimation Workbook – 2024-25', 'Analytical Workbook', 'Statistical Officer', 'National Accounts Unit', 'National Accounts', 'Advanced', 'Completed', 'Economic Statistics | Data Analysis & Interpretation | Estimation Methods | Spreadsheet Analysis | Quality Assurance', 'Internal Work Artifact', 1, 1, 'Analytical workbook used to estimate district-level economic output across major economic activities.', 'estimation | sector aggregation | spreadsheet analysis | validation');
INSERT INTO work_artifacts VALUES ('WA-2025-006', 'Statistical Dashboard Requirements Specification', 'Requirements Document', 'Data Analyst', 'Statistical Informatics Cell', 'Statistical IT Systems', 'Intermediate', 'Approved', 'Data Visualization | Requirements Analysis | Dashboard Design | Data Interpretation | Communication', 'Internal Work Artifact', 1, 1, 'Functional requirements for an internal dashboard displaying statistical indicators, trends, filters and district comparisons.', 'dashboard design | KPIs | visualization | requirements gathering');
INSERT INTO work_artifacts VALUES ('WA-2025-007', 'Agricultural Crop Yield Estimation Report – Kharif 2025', 'Statistical Report', 'Research Officer', 'Agriculture Statistics Division', 'Agricultural Statistics', 'Intermediate', 'Completed', 'Agricultural Statistics | Estimation Methods | Data Interpretation | Survey Methodology | Report Writing', 'Internal Work Artifact', 1, 1, 'Report analysing crop area, production and yield estimates for major Kharif crops across selected districts.', 'crop yield | estimation | district comparison | statistical reporting');
INSERT INTO work_artifacts VALUES ('WA-2025-008', 'Automated Data Validation Rules Catalogue', 'Technical Specification', 'Technical Officer', 'Data Processing Division', 'Data Engineering', 'Advanced', 'Approved', 'Data Validation | SQL | Python | Data Quality Management | Automation', 'Internal Work Artifact', 1, 1, 'Catalogue of automated validation rules for range checks, referential checks, duplicate detection and cross-field consistency.', 'SQL | Python | validation rules | automation | data quality');
INSERT INTO work_artifacts VALUES ('WA-2025-009', 'Annual Education Statistics Analytical Brief', 'Analytical Brief', 'Assistant Director', 'Social Statistics Division', 'Education Statistics', 'Intermediate', 'Completed', 'Data Interpretation | Statistical Analysis | Report Writing | Data Visualization | Indicator Analysis', 'Internal Work Artifact', 1, 1, 'Analytical brief comparing enrolment, dropout, pupil-teacher ratio and school infrastructure indicators.', 'education indicators | trend analysis | charts | policy interpretation');
INSERT INTO work_artifacts VALUES ('WA-2025-010', 'Metadata Dictionary for Official Statistical Indicators', 'Data Dictionary', 'Data Analyst', 'Statistical Standards Unit', 'Statistical Standards', 'Intermediate', 'Approved', 'Metadata Management | Data Standards | Documentation | Data Governance | Statistical Concepts', 'Internal Work Artifact', 1, 1, 'Standardised definitions, units, calculation methods, source systems and update frequency for official statistical indicators.', 'metadata | data dictionary | standards | governance');
INSERT INTO work_artifacts VALUES ('WA-2025-011', 'Labour Force Survey Field Inspection Checklist', 'Inspection Checklist', 'Field Supervisor', 'Field Operations Division', 'Field Survey Operations', 'Beginner', 'Active', 'Survey Operations | Data Quality Management | Field Inspection | Communication | Documentation', 'Internal Work Artifact', 1, 1, 'Checklist for supervising field investigators and verifying survey procedures, respondent coverage and questionnaire completeness.', 'field inspection | survey protocols | quality checks | documentation');
INSERT INTO work_artifacts VALUES ('WA-2025-012', 'Seasonal Adjustment Methodology Review', 'Methodology Review', 'Research Officer', 'Economic Analysis Division', 'Time Series Statistics', 'Advanced', 'Under Review', 'Time Series Analysis | Seasonal Adjustment | Statistical Modelling | Data Interpretation | Methodology Review', 'Internal Work Artifact', 1, 1, 'Review of seasonal patterns and proposed methodology for producing seasonally adjusted economic indicators.', 'time series | seasonality | modelling | trend-cycle analysis');
INSERT INTO work_artifacts VALUES ('WA-2025-013', 'Official Statistics Data Release Calendar', 'Planning Document', 'Administrative Officer', 'Statistical Coordination Cell', 'Statistical Coordination', 'Beginner', 'Approved', 'Planning & Coordination | Documentation | Communication | Data Governance', 'Internal Work Artifact', 1, 1, 'Annual calendar defining planned release dates, responsible units, review milestones and publication dependencies.', 'planning | coordination | release management | documentation');
INSERT INTO work_artifacts VALUES ('WA-2025-014', 'Data Privacy and Confidentiality Procedure for Survey Microdata', 'Standard Operating Procedure', 'Statistical Officer', 'Data Governance Unit', 'Data Governance', 'Advanced', 'Approved', 'Data Governance | Statistical Confidentiality | Data Security | Risk Management | Documentation', 'Internal Work Artifact', 1, 1, 'Procedure describing access controls, anonymisation, secure handling and controlled sharing of survey microdata.', 'confidentiality | anonymisation | access control | risk assessment');
INSERT INTO work_artifacts VALUES ('WA-2025-015', 'Monthly Industrial Production Trend Analysis – August 2025', 'Analytical Report', 'Statistical Officer', 'Industrial Statistics Division', 'Industrial Statistics', 'Intermediate', 'Completed', 'Time Series Analysis | Data Visualization | Trend Analysis | Statistical Interpretation | Report Writing', 'Internal Work Artifact', 1, 1, 'Monthly analysis of industrial production indices with year-on-year and month-on-month comparisons.', 'IIP | trend analysis | time series | visualization | report writing');
